# Generated by Django 2.2 on 2020-06-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='size',
            field=models.CharField(default='', max_length=20),
        ),
    ]
