# Generated by Django 2.2 on 2021-03-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
