# Generated by Django 2.2 on 2021-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210320_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
