# Generated by Django 2.2 on 2021-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210320_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequest',
            name='filetype',
            field=models.CharField(choices=[('tutorials', 'Tutorials'), ('books', 'Books'), ('notes', 'Notes'), ('exampapers', 'Examination Papers')], max_length=20),
        ),
        migrations.AlterField(
            model_name='upload',
            name='filetype',
            field=models.CharField(choices=[('tutorials', 'Tutorials'), ('books', 'Books'), ('notes', 'Notes'), ('exampapers', 'Examination Papers')], default='', max_length=20),
        ),
    ]
