# Generated by Django 2.2 on 2020-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200531_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notifications',
            name='target',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
