# Generated by Django 2.2 on 2020-07-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200701_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
