version: '3'
services:
  db:
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    volumes:
        - ".:/studyportal-nexus:rw"
    environment:
      POSTGRES_DB: "studyportal"
      POSTGRES_USER: "studyportal"
      POSTGRES_PASSWORD: "studyportal"
      POSTGRES_HOST: "0.0.0.0"
    healthcheck:
      test: "pg_isready -U studyportal -d studyportal"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    ports:
      - "9200:9200"
    environment:
      # disable XPack
      # https://www.elastic.co/guide/en/elasticsearch/reference/5.3/docker.html#_security_note
      - xpack.security.enabled=false
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl -si -XGET 'localhost:9200/_cluster/health?pretty' | grep -qE 'yellow|green'"]
      interval: 10s
      timeout: 60s
      retries: 10
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis:
    container_name: redis
    image: redis
    ports:
      - "6389:6389"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  web:
    build: ./
    image: studyportal-nexus
    command: bash -c 'python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py search_index --rebuild -f &&
             python manage.py runserver 0.0.0.0:8005'
    container_name: studyportal-nexus
    volumes:
        - ".:/studyportal-nexus:rw"
    ports:
      - "8005:8005"
    depends_on:
      - db
      - es
      - redis
    extra_hosts:
      - "arceus.sdslabs.local:172.25.158.16"
      - "falcon.sdslabs.local:172.25.158.16"
    environment:
      DJANGO_DATABASE_NAME: "studyportal"
      DJANGO_DATABASE_USER: "studyportal"
      DJANGO_DATABASE_PASSWORD: "studyportal"
      DJANGO_DATABASE_HOST: "db"
      PYTHONUNBUFFERED: "0"
      DJANGO_DEBUG_ENABLED: "True"
      ELASTICSEARCH_URL: "es"
      ELASTICSEARCH_PORT: "9200"
      DISABLE_GLOBAL_THROTTLING: "True"
      ROOT_SHORTENING_URL: "localhost:8005"
      DEVELOPMENT_MODE: "True"
    stdin_open: true
    tty: true
