# Generated by Django 2.2 on 2019-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="url",
            field=models.CharField(default="", max_length=100),
        ),
    ]
