# Generated by Django 2.2.4 on 2019-08-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0002_department_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
    ]
