# Generated by Django 2.2.4 on 2019-10-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0006_auto_20191003_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="fileext",
            field=models.CharField(default="", max_length=5),
        ),
    ]
