# Generated by Django 2.2.4 on 2019-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0008_auto_20191003_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(default="", upload_to=""),
        ),
    ]
