# Generated by Django 2.2.4 on 2019-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0009_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(default="", upload_to="files"),
        ),
    ]
