# Generated by Django 2.2.4 on 2019-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_auto_20191007_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to='./files'),
        ),
    ]
