# Generated by Django 2.2.4 on 2019-10-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0012_auto_20191007_1610"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="fileext",
        ),
        migrations.RemoveField(
            model_name="file",
            name="size",
        ),
        migrations.RemoveField(
            model_name="file",
            name="title",
        ),
    ]
