# Generated by Django 2.2.4 on 2019-10-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_auto_20191007_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fileext',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
    ]
