# Generated by Django 2.2.6 on 2019-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_auto_20191014_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloads',
            field=models.IntegerField(editable=False),
        ),
    ]
