# Generated by Django 2.2.6 on 2019-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileext',
            field=models.CharField(default='', max_length=10),
        ),
    ]
