# Generated by Django 2.2.6 on 2019-10-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0021_file_fileext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="driveid",
            field=models.CharField(default="", max_length=50),
        ),
    ]
