# Generated by Django 2.2.6 on 2019-11-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0026_auto_20191126_1730"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="finalized",
            field=models.BooleanField(default=False),
        ),
    ]
