# Generated by Django 2.2.6 on 2019-12-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0027_file_finalized'),
        ('rest_api', '0019_auto_20191022_1439'),
    ]

    operations = [
    ]
