# Generated by Django 2.2.6 on 2019-12-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0030_upload_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="departmennt",
            new_name="department",
        ),
    ]
