# Generated by Django 2.2 on 2020-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0033_auto_20191228_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(max_length=500),
        ),
    ]
