# Generated by Django 2.2 on 2020-01-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0034_auto_20200127_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='filetype',
            field=models.CharField(choices=[('Tutorial', 'tutorials'), ('Book', 'books'), ('Notes', 'notes'), ('Examination Papers', 'exampapers')], default='', max_length=20),
        ),
    ]
