# Generated by Django 2.2 on 2020-02-13 09:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0036_remove_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
