# Generated by Django 2.2 on 2020-02-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0039_upload_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request",
            new_name="FileRequest",
        ),
    ]
