# Generated by Django 2.2 on 2020-02-18 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0041_courserequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserequest",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
