# Generated by Django 2.2 on 2020-02-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0042_courserequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
            preserve_default=False,
        ),
    ]
