# Generated by Django 2.2 on 2020-04-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0043_upload_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filerequest",
            name="course",
        ),
        migrations.RemoveField(
            model_name="filerequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="course",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="user",
        ),
        migrations.DeleteModel(
            name="CourseRequest",
        ),
        migrations.DeleteModel(
            name="FileRequest",
        ),
        migrations.DeleteModel(
            name="Upload",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
