# Generated by Django 2.2 on 2020-04-22 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0044_auto_20200407_2005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="date_modified",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
