# Generated by Django 2.2 on 2020-04-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0045_auto_20200422_0506"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="date_modified",
            field=models.DateField(auto_now=True),
        ),
    ]
