# Generated by Django 2.2 on 2021-03-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0047_department_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="image",
            field=models.ImageField(blank=True, upload_to="thumbnail"),
        ),
    ]
