# Generated by Django 2.2 on 2021-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0049_remove_department_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('tutorials', 'Tutorial'), ('books', 'Book'), ('notes', 'Notes'), ('exampapers', 'Examination Papers')], max_length=20),
        ),
    ]
