# Generated by Django 2.2 on 2021-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('tutorials', 'Tutorials'), ('books', 'Books'), ('notes', 'Notes'), ('exampapers', 'Examination Papers')], max_length=20),
        ),
    ]
