name: Python CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install PostgreSQL 10 client
      run: |
        sudo apt-get -yqq install libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest && pip install requests
    - name: Start docker
      run: |
        cp .env.sample .env
        docker container prune -f
        docker-compose up -d
        bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8005/api/v1)" != "200" ]]; do sleep 10; done'
        ./ingest.sh
        bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8005/api/v1/search/?q=test)" != "200" ]]; do sleep 5; done'
    - name: Run Tests
      run: |
        pytest
